import type { Product, ProductCategory } from "../types";

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  "Membranes", "Liquid Coatings", "Primers & Bitumen", "Sealants",
  "Admixtures & Repair", "Tile Adhesives & Grouts", "Accessories",
];

export const CATEGORY_BLURBS: Record<ProductCategory, string> = {
  "Membranes": "APP and SBS modified bituminous sheet membranes for roofs, basements and foundations.",
  "Liquid Coatings": "Seamless brush, roller and spray-applied membranes for wet areas and awkward details.",
  "Primers & Bitumen": "Primers and industrial bitumen grades that bond and build up waterproofing systems.",
  "Sealants": "Flexible sealants for expansion joints, cracks and construction joints.",
  "Admixtures & Repair": "Concrete admixtures, curing compounds and bonding agents for dense, durable concrete.",
  "Tile Adhesives & Grouts": "Adhesives and grouts that keep tiled wet areas watertight.",
  "Accessories": "Protection layers that keep the membrane intact after installation.",
};

export const PRODUCTS: Product[] = [
  {
    slug: "torch-4000", name: "RoyalGrip Torch 4000", category: "Membranes", featured: true,
    tagline: "APP-modified torch-on membrane for roofs, decks and foundations.",
    description: "A plastomeric (APP) modified bituminous membrane reinforced with a spunbonded polyester carrier. It is torch-welded to the primed slab and at every lap, forming one continuous, fully bonded waterproof layer that tolerates high roof temperatures.",
    size: "3mm / 4mm / 5mm · 1m × 10m roll",
    specs: ["Polyester reinforced core", "Softening point 150°C", "Elongation ≥ 45%"],
    applications: ["Flat concrete roofs and terraces", "Basement walls and rafts", "Podium decks and parking slabs", "Bridge decks under asphalt"],
    method: "Prime the clean, dry substrate, then unroll and torch the underside until the bitumen flows. Overlap side laps 100mm and end laps 150mm and seal the seams with a trowel.",
  },
  {
    slug: "elastoseal-sa", name: "RoyalGrip ElastoSeal SA", category: "Membranes", featured: true,
    tagline: "SBS-modified self-adhesive membrane, cold-applied without a flame.",
    description: "An elastomeric (SBS) modified bituminous membrane with a peel-off release film and a cross-laminated HDPE top face. It bonds on contact, so it suits sites where torches are not allowed and stays flexible over moving substrates.",
    size: "1.5mm / 2mm · 1m × 15m roll",
    specs: ["Flame-free installation", "Self-sealing around fixings", "Flexible at low temperatures"],
    applications: ["Basement and retaining walls", "Foundations and plinth beams", "Confined or flammable work areas", "Timber and metal substrates"],
    method: "Prime the surface, peel back the release film and press the membrane into place, rolling firmly from the centre outwards. Overlap laps 75mm and roll the seams.",
  },
  {
    slug: "slateshield", name: "RoyalGrip SlateShield", category: "Membranes", featured: true,
    tagline: "Mineral-granule surface for permanently exposed rooftops.",
    description: "A torch-applied APP membrane factory-finished with mineral slate granules. The granules shield the bitumen from UV, so the roof needs no screed or tiles on top and can be left exposed.",
    size: "4mm · 1m × 10m roll",
    specs: ["UV-stable slate finish", "No screed required", "Charcoal & terracotta"],
    applications: ["Exposed flat and low-slope roofs", "Factory and warehouse roofs", "Re-roofing over old membranes", "Parapet and upstand capping"],
    method: "Torch-apply as the cap sheet over a primed slab or base layer. Bleed a 10mm bead of bitumen at each lap for a watertight seam.",
  },
  {
    slug: "aluguard", name: "RoyalGrip AluGuard", category: "Membranes",
    tagline: "Aluminium-faced membrane that reflects heat off the slab.",
    description: "A torch-applied modified bitumen membrane faced with embossed aluminium foil. The reflective face cuts solar heat gain, lowering the temperature of the slab and the rooms below while protecting the bitumen from UV.",
    size: "4mm · 1m × 10m roll",
    specs: ["Reflects ~70% solar gain", "Lowers roof temp 8–12°C", "Embossed foil face"],
    applications: ["Exposed roofs in hot climates", "Top-floor residential roofs", "Cold stores and air-conditioned buildings", "Metal and concrete gutters"],
    method: "Torch-apply as an exposed cap sheet onto a primed substrate. Avoid direct flame on the foil face and seal laps with aluminium bitumen paint.",
  },
  {
    slug: "rootblock", name: "RoyalGrip RootBlock", category: "Membranes",
    tagline: "Anti-root membrane for planters, lawns and green roofs.",
    description: "A torch-applied membrane whose bitumen compound contains a root-inhibiting additive. Roots are turned away at the surface instead of penetrating the waterproofing, without harming the plants.",
    size: "4mm · 1m × 10m roll",
    specs: ["Chemical root barrier", "Planter-box detailing", "Garden-deck tested"],
    applications: ["Roof gardens and green roofs", "Planter boxes", "Landscaped podium decks", "Lawns over basements"],
    method: "Install as the top layer of a two-layer system, fully torch-bonded, then cover with protection board and a drainage layer before placing soil.",
  },
  {
    slug: "dpc-membrane", name: "RoyalGrip DPC Membrane", category: "Membranes", featured: true,
    tagline: "Damp proof course that stops rising damp at plinth level.",
    description: "A heavy-duty bituminous damp proof course laid across the full width of the wall at plinth level. It blocks ground moisture from climbing through brickwork, the cause of peeling paint and salt deposits on ground-floor walls.",
    size: "9\" / 13.5\" / 18\" widths · 10m roll",
    specs: ["Blocks rising damp", "Withstands wall loading", "Rot and salt resistant"],
    applications: ["Plinth-level damp proof course", "Below ground-floor slabs", "Under parapet copings", "Around door and window sills"],
    method: "Lay on a level mortar bed across the full wall width, lap lengths at least 100mm and bond the laps before continuing the masonry.",
  },
  {
    slug: "flexcoat", name: "RoyalGrip FlexCoat", category: "Liquid Coatings", featured: true,
    tagline: "Acrylic elastomeric liquid membrane for wet areas and awkward geometry.",
    description: "A single-component acrylic coating that cures into a seamless, flexible, UV-resistant membrane. It follows pipes, corners and upstands that sheet membranes cannot, and can be tiled over.",
    size: "5kg / 20kg pail",
    specs: ["Brush, roller or spray", "Bridges 2mm cracks", "Tile-over compatible"],
    applications: ["Bathrooms, kitchens and balconies", "Roof details and upstands", "Exterior walls and parapets", "Over existing sound screeds"],
    method: "Apply two or more coats at right angles to each other on a primed, clean surface, embedding fabric at corners and cracks. Allow each coat to dry before the next.",
  },
  {
    slug: "pu-shield", name: "RoyalGrip PU Shield", category: "Liquid Coatings",
    tagline: "Polyurethane liquid membrane with high elasticity for decks and tanks.",
    description: "A single-component polyurethane coating that cures to a tough, highly elastic, fully bonded membrane. It bridges moving cracks and resists standing water, making it suited to decks, tanks and steel surfaces.",
    size: "20kg pail",
    specs: ["High elongation", "Resists ponding water", "Bonds to concrete and steel"],
    applications: ["Water tanks and reservoirs", "Podiums and balconies", "Metal roofs and gutters", "Exposed roof decks"],
    method: "Prime the substrate and apply by roller or squeegee in two coats to the specified thickness. Broadcast sand into the final coat where a screed or tiles will follow.",
  },
  {
    slug: "rubbercoat", name: "RoyalGrip RubberCoat", category: "Liquid Coatings",
    tagline: "Rubberised bitumen coating for foundations and quick repairs.",
    description: "A cold-applied, rubber-modified bitumen emulsion that dries to a flexible black waterproof film. An economical choice for buried concrete and for patching old bituminous roofs.",
    size: "20kg pail / 200kg drum",
    specs: ["Cold-applied, no heating", "Water-based emulsion", "Flexible black film"],
    applications: ["Foundations and footings", "Retaining walls before backfill", "Patch repairs on bitumen roofs", "Damp-proofing under floor screeds"],
    method: "Stir well and apply two coats by brush or roller on a damp-free surface, the first thinned as a primer coat. Protect the cured film before backfilling.",
  },
  {
    slug: "bitumen-primer", name: "RoyalGrip Bitumen Primer", category: "Primers & Bitumen", featured: true,
    tagline: "Fast-drying primer that locks the membrane onto concrete.",
    description: "A penetrating bituminous primer that seals dust and pores in concrete so torch-on and self-adhesive membranes achieve a full bond. Used before every sheet membrane installation.",
    size: "18L pail / 200L drum",
    specs: ["Touch-dry in 60 min", "Coverage 5–6 m²/L", "Low-odour formulation"],
    applications: ["Before torch-applied membranes", "Before self-adhesive membranes", "Concrete, screed and masonry", "Damp-proofing of buried concrete"],
    method: "Apply one even coat by brush, roller or spray to a clean, dry surface and allow it to dry fully before laying membrane.",
  },
  {
    slug: "oxidized-bitumen", name: "RoyalGrip Oxidized Bitumen 10/20", category: "Primers & Bitumen",
    tagline: "Hard, hot-applied blown bitumen for heavy-duty waterproofing.",
    description: "A solid blown-grade bitumen with a low penetration value and high softening point. It is melted and hot-poured as a tough, heat-resistant waterproofing and bonding layer.",
    size: "25kg bag / 200kg drum",
    specs: ["Penetration 10–20 dmm", "High softening point", "Hot-applied grade"],
    applications: ["Built-up roofing felt systems", "Pipe coating and tank bases", "Bonding insulation boards", "Industrial sealing and binding"],
    method: "Heat gradually in a bitumen boiler to working temperature, stirring to avoid local overheating, and pour or mop onto a primed surface.",
  },
  {
    slug: "gripflex-pu", name: "GripFlex PU Sealant", category: "Sealants",
    tagline: "Polyurethane sealant for moving joints and cracks.",
    description: "A single-component, gun-grade polyurethane sealant that cures to a durable elastic rubber. It keeps joints watertight while the structure expands and contracts with temperature.",
    size: "600ml sausage",
    specs: ["Permanently elastic", "Paintable when cured", "Bonds to most substrates"],
    applications: ["Expansion and construction joints", "Window and door perimeters", "Pipe penetrations", "Precast panel joints"],
    method: "Clean the joint, insert a backer rod, prime porous surfaces and gun the sealant in. Tool it smooth before it skins.",
  },
  {
    slug: "gripjoint-compound", name: "GripJoint Sealing Compound", category: "Sealants",
    tagline: "Hot-poured rubberised bitumen for horizontal joints.",
    description: "A rubber-modified bituminous compound poured hot into horizontal joints. It stays flexible through summer heat and winter cold, sealing joints in slabs and pavements against water and grit.",
    size: "20kg block",
    specs: ["Hot-poured", "Flexible in heat and cold", "Resists water and grit"],
    applications: ["Concrete road and pavement joints", "Industrial floor joints", "Roof expansion joints", "Canal and channel linings"],
    method: "Melt in a jacketed boiler, clean and prime the joint, then pour slightly below the surface to allow for expansion.",
  },
  {
    slug: "gripplast-sp", name: "GripPlast SP", category: "Admixtures & Repair",
    tagline: "High-range superplasticiser for dense, low-permeability concrete.",
    description: "A water-reducing admixture that lets concrete flow at a much lower water content. Less water means fewer capillary pores, higher strength and concrete that resists water on its own.",
    size: "20L can / 200L drum",
    specs: ["Up to 25% water cut", "Chloride free", "ASTM C494 Type F"],
    applications: ["Raft foundations and basements", "Water-retaining structures", "Pumped and ready-mix concrete", "High-strength structural members"],
    method: "Add to the mixing water or directly into the mixer at the dosage confirmed by site trials.",
  },
  {
    slug: "gripcure-w", name: "GripCure W", category: "Admixtures & Repair",
    tagline: "Curing compound that holds moisture in fresh slabs and pavements.",
    description: "A spray-applied membrane-forming curing compound. It traps mix water in fresh concrete so cement hydrates fully, cutting the plastic shrinkage cracks that later become leak paths.",
    size: "20L can / 200L drum",
    specs: ["Retains ≥ 90% moisture", "Single-coat spray", "Reduces plastic cracking"],
    applications: ["Roof slabs in hot weather", "Roads and pavements", "Large floor pours", "Vertical surfaces after stripping"],
    method: "Spray one uniform coat as soon as surface water has disappeared from the fresh concrete.",
  },
  {
    slug: "gripproof-wp", name: "GripProof WP", category: "Admixtures & Repair",
    tagline: "Integral waterproofing admixture for concrete, plaster and mortar.",
    description: "A liquid admixture that blocks capillary pores from within the mix. It reduces water absorption, dampness and efflorescence, waterproofing concrete and plaster from the inside out.",
    size: "1L / 5L / 20L can",
    specs: ["Blocks capillary pores", "Reduces efflorescence", "Dosed per cement bag"],
    applications: ["Water tanks and basements", "External plaster and render", "Bathroom floor screeds", "Roof screeds"],
    method: "Mix into the gauging water before adding to the dry batch, at the dosage stated per bag of cement.",
  },
  {
    slug: "gripbond-sbr", name: "GripBond SBR", category: "Admixtures & Repair",
    tagline: "SBR latex bonding agent and waterproofing additive.",
    description: "A styrene butadiene rubber latex that improves the adhesion, tensile strength and water resistance of cement mortars. Used to bond new concrete to old and to make repair mortars that stay put.",
    size: "1L / 5L / 20L can",
    specs: ["Bonds new to old concrete", "Improves flexural strength", "Reduces permeability"],
    applications: ["Concrete patch repairs", "Bonding slurry under screeds", "Waterproof renders", "Tank lining mortars"],
    method: "Brush on as a bonding slurry mixed with cement, or add to the gauging water of repair mortar and place while the slurry is still tacky.",
  },
  {
    slug: "griptile-bond", name: "GripTile Bond", category: "Tile Adhesives & Grouts",
    tagline: "Polymer-modified tile adhesive for wet and dry areas.",
    description: "A cement-based, polymer-modified adhesive that fixes ceramic, porcelain and stone tiles with full bed contact. It leaves no hollow pockets beneath the tile for water to collect in.",
    size: "20kg bag",
    specs: ["Non-slip on walls", "Suitable for wet areas", "Extended open time"],
    applications: ["Bathroom floors and walls", "Kitchens and balconies", "Large-format porcelain", "Over cured liquid membranes"],
    method: "Mix with clean water, comb onto the surface with a notched trowel and press tiles in with a slight twist.",
  },
  {
    slug: "griptile-grout-ep", name: "GripTile Grout EP", category: "Tile Adhesives & Grouts",
    tagline: "Epoxy tile grout that is waterproof and stain-proof.",
    description: "A three-component epoxy grout that cures to a hard, non-porous joint. It does not absorb water or stains and stands up to cleaning chemicals, so tiled joints stop being a leak path.",
    size: "5kg kit",
    specs: ["Non-porous finish", "Chemical resistant", "Stain-proof joints"],
    applications: ["Showers and bathrooms", "Swimming pools", "Commercial kitchens", "Food and pharma plants"],
    method: "Blend the components fully, work into the joints with a rubber float and clean off residue before it sets.",
  },
  {
    slug: "protection-board", name: "GripBoard Protection Board", category: "Accessories",
    tagline: "Protects the installed membrane from backfill and site traffic.",
    description: "A semi-rigid bituminous board laid over the finished membrane. It takes the punishment of backfill, reinforcement fixing and foot traffic so the waterproofing underneath stays intact.",
    size: "3mm / 6mm · 1m × 2m sheet",
    specs: ["Resists puncture", "Compatible with bitumen", "Cuts with a knife"],
    applications: ["Basement walls before backfill", "Over rafts before steel fixing", "Under roof screeds", "Planter boxes and podiums"],
    method: "Spot-bond over the completed membrane with butt joints, then proceed with backfill or screed.",
  },
];

export function productBySlug(slug: string | undefined) {
  return PRODUCTS.find((p) => p.slug === slug);
}
